micronaut.application.name=micronaut-jooq
micronaut.server.port=8080

datasources.default.url=${JDBC_URL:`jdbc:postgresql://localhost:5432/fruits`}
datasources.default.username=${DB_USERNAME:fruits}
datasources.default.password=${DB_PASSWORD:fruits}
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.dialect=POSTGRES
datasources.default.maximum-pool-size=50
datasources.default.minimum-idle=10
datasources.default.connection-timeout=30000

jooq.datasources.default.sql-dialect=POSTGRES

endpoints.health.enabled=true
endpoints.health.sensitive=false
endpoints.health.details-visible=ANONYMOUS

otel.service.name=micronaut-jooq
otel.traces.exporter=otlp
otel.traces.sampler=traceidratio
otel.traces.sampler.arg=0.1
otel.metrics.exporter=otlp
otel.logs.exporter=none
