// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Fruit is the predicate function for fruit builders.
type Fruit func(*sql.Selector)

// Store is the predicate function for store builders.
type Store func(*sql.Selector)

// StoreFruitPrice is the predicate function for storefruitprice builders.
type StoreFruitPrice func(*sql.Selector)
