// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FruitsColumns holds the columns for the "fruits" table.
	FruitsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
	}
	// FruitsTable holds the schema information for the "fruits" table.
	FruitsTable = &schema.Table{
		Name:       "fruits",
		Columns:    FruitsColumns,
		PrimaryKey: []*schema.Column{FruitsColumns[0]},
	}
	// StoresColumns holds the columns for the "stores" table.
	StoresColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "currency", Type: field.TypeString},
		{Name: "address", Type: field.TypeString},
		{Name: "city", Type: field.TypeString},
		{Name: "country", Type: field.TypeString},
	}
	// StoresTable holds the schema information for the "stores" table.
	StoresTable = &schema.Table{
		Name:       "stores",
		Columns:    StoresColumns,
		PrimaryKey: []*schema.Column{StoresColumns[0]},
	}
	// StoreFruitPricesColumns holds the columns for the "store_fruit_prices" table.
	StoreFruitPricesColumns = []*schema.Column{
		{Name: "fruit_id", Type: field.TypeInt64, Increment: true},
		{Name: "price", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric(12,2)"}},
		{Name: "store_id", Type: field.TypeInt64},
	}
	// StoreFruitPricesTable holds the schema information for the "store_fruit_prices" table.
	StoreFruitPricesTable = &schema.Table{
		Name:       "store_fruit_prices",
		Columns:    StoreFruitPricesColumns,
		PrimaryKey: []*schema.Column{StoreFruitPricesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "store_fruit_prices_stores_fruit_prices",
				Columns:    []*schema.Column{StoreFruitPricesColumns[2]},
				RefColumns: []*schema.Column{StoresColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FruitsTable,
		StoresTable,
		StoreFruitPricesTable,
	}
)

func init() {
	FruitsTable.Annotation = &entsql.Annotation{
		Table: "fruits",
	}
	StoresTable.Annotation = &entsql.Annotation{
		Table: "stores",
	}
	StoreFruitPricesTable.ForeignKeys[0].RefTable = StoresTable
	StoreFruitPricesTable.Annotation = &entsql.Annotation{
		Table: "store_fruit_prices",
	}
}
