// Code generated by ent, DO NOT EDIT.

package storefruitprice

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/quarkusio/spring-quarkus-perf-comparison/golang/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(sql.FieldLTE(FieldID, id))
}

// StoreID applies equality check predicate on the "store_id" field. It's identical to StoreIDEQ.
func StoreID(v int64) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(sql.FieldEQ(FieldStoreID, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(sql.FieldEQ(FieldPrice, v))
}

// StoreIDEQ applies the EQ predicate on the "store_id" field.
func StoreIDEQ(v int64) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(sql.FieldEQ(FieldStoreID, v))
}

// StoreIDNEQ applies the NEQ predicate on the "store_id" field.
func StoreIDNEQ(v int64) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(sql.FieldNEQ(FieldStoreID, v))
}

// StoreIDIn applies the In predicate on the "store_id" field.
func StoreIDIn(vs ...int64) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(sql.FieldIn(FieldStoreID, vs...))
}

// StoreIDNotIn applies the NotIn predicate on the "store_id" field.
func StoreIDNotIn(vs ...int64) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(sql.FieldNotIn(FieldStoreID, vs...))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(sql.FieldLTE(FieldPrice, v))
}

// HasStore applies the HasEdge predicate on the "store" edge.
func HasStore() predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, StoreTable, StoreColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasStoreWith applies the HasEdge predicate on the "store" edge with a given conditions (other predicates).
func HasStoreWith(preds ...predicate.Store) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(func(s *sql.Selector) {
		step := newStoreStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StoreFruitPrice) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StoreFruitPrice) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StoreFruitPrice) predicate.StoreFruitPrice {
	return predicate.StoreFruitPrice(sql.NotPredicates(p))
}
