// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/quarkusio/spring-quarkus-perf-comparison/golang/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/quarkusio/spring-quarkus-perf-comparison/golang/ent/fruit"
	"github.com/quarkusio/spring-quarkus-perf-comparison/golang/ent/store"
	"github.com/quarkusio/spring-quarkus-perf-comparison/golang/ent/storefruitprice"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Fruit is the client for interacting with the Fruit builders.
	Fruit *FruitClient
	// Store is the client for interacting with the Store builders.
	Store *StoreClient
	// StoreFruitPrice is the client for interacting with the StoreFruitPrice builders.
	StoreFruitPrice *StoreFruitPriceClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Fruit = NewFruitClient(c.config)
	c.Store = NewStoreClient(c.config)
	c.StoreFruitPrice = NewStoreFruitPriceClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		Fruit:           NewFruitClient(cfg),
		Store:           NewStoreClient(cfg),
		StoreFruitPrice: NewStoreFruitPriceClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:             ctx,
		config:          cfg,
		Fruit:           NewFruitClient(cfg),
		Store:           NewStoreClient(cfg),
		StoreFruitPrice: NewStoreFruitPriceClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Fruit.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Fruit.Use(hooks...)
	c.Store.Use(hooks...)
	c.StoreFruitPrice.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Fruit.Intercept(interceptors...)
	c.Store.Intercept(interceptors...)
	c.StoreFruitPrice.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *FruitMutation:
		return c.Fruit.mutate(ctx, m)
	case *StoreMutation:
		return c.Store.mutate(ctx, m)
	case *StoreFruitPriceMutation:
		return c.StoreFruitPrice.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// FruitClient is a client for the Fruit schema.
type FruitClient struct {
	config
}

// NewFruitClient returns a client for the Fruit from the given config.
func NewFruitClient(c config) *FruitClient {
	return &FruitClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `fruit.Hooks(f(g(h())))`.
func (c *FruitClient) Use(hooks ...Hook) {
	c.hooks.Fruit = append(c.hooks.Fruit, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `fruit.Intercept(f(g(h())))`.
func (c *FruitClient) Intercept(interceptors ...Interceptor) {
	c.inters.Fruit = append(c.inters.Fruit, interceptors...)
}

// Create returns a builder for creating a Fruit entity.
func (c *FruitClient) Create() *FruitCreate {
	mutation := newFruitMutation(c.config, OpCreate)
	return &FruitCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Fruit entities.
func (c *FruitClient) CreateBulk(builders ...*FruitCreate) *FruitCreateBulk {
	return &FruitCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FruitClient) MapCreateBulk(slice any, setFunc func(*FruitCreate, int)) *FruitCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FruitCreateBulk{err: fmt.Errorf("calling to FruitClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FruitCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FruitCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Fruit.
func (c *FruitClient) Update() *FruitUpdate {
	mutation := newFruitMutation(c.config, OpUpdate)
	return &FruitUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FruitClient) UpdateOne(_m *Fruit) *FruitUpdateOne {
	mutation := newFruitMutation(c.config, OpUpdateOne, withFruit(_m))
	return &FruitUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FruitClient) UpdateOneID(id int64) *FruitUpdateOne {
	mutation := newFruitMutation(c.config, OpUpdateOne, withFruitID(id))
	return &FruitUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Fruit.
func (c *FruitClient) Delete() *FruitDelete {
	mutation := newFruitMutation(c.config, OpDelete)
	return &FruitDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FruitClient) DeleteOne(_m *Fruit) *FruitDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FruitClient) DeleteOneID(id int64) *FruitDeleteOne {
	builder := c.Delete().Where(fruit.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FruitDeleteOne{builder}
}

// Query returns a query builder for Fruit.
func (c *FruitClient) Query() *FruitQuery {
	return &FruitQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFruit},
		inters: c.Interceptors(),
	}
}

// Get returns a Fruit entity by its id.
func (c *FruitClient) Get(ctx context.Context, id int64) (*Fruit, error) {
	return c.Query().Where(fruit.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FruitClient) GetX(ctx context.Context, id int64) *Fruit {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *FruitClient) Hooks() []Hook {
	return c.hooks.Fruit
}

// Interceptors returns the client interceptors.
func (c *FruitClient) Interceptors() []Interceptor {
	return c.inters.Fruit
}

func (c *FruitClient) mutate(ctx context.Context, m *FruitMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FruitCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FruitUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FruitUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FruitDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Fruit mutation op: %q", m.Op())
	}
}

// StoreClient is a client for the Store schema.
type StoreClient struct {
	config
}

// NewStoreClient returns a client for the Store from the given config.
func NewStoreClient(c config) *StoreClient {
	return &StoreClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `store.Hooks(f(g(h())))`.
func (c *StoreClient) Use(hooks ...Hook) {
	c.hooks.Store = append(c.hooks.Store, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `store.Intercept(f(g(h())))`.
func (c *StoreClient) Intercept(interceptors ...Interceptor) {
	c.inters.Store = append(c.inters.Store, interceptors...)
}

// Create returns a builder for creating a Store entity.
func (c *StoreClient) Create() *StoreCreate {
	mutation := newStoreMutation(c.config, OpCreate)
	return &StoreCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Store entities.
func (c *StoreClient) CreateBulk(builders ...*StoreCreate) *StoreCreateBulk {
	return &StoreCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *StoreClient) MapCreateBulk(slice any, setFunc func(*StoreCreate, int)) *StoreCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &StoreCreateBulk{err: fmt.Errorf("calling to StoreClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*StoreCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &StoreCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Store.
func (c *StoreClient) Update() *StoreUpdate {
	mutation := newStoreMutation(c.config, OpUpdate)
	return &StoreUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *StoreClient) UpdateOne(_m *Store) *StoreUpdateOne {
	mutation := newStoreMutation(c.config, OpUpdateOne, withStore(_m))
	return &StoreUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *StoreClient) UpdateOneID(id int64) *StoreUpdateOne {
	mutation := newStoreMutation(c.config, OpUpdateOne, withStoreID(id))
	return &StoreUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Store.
func (c *StoreClient) Delete() *StoreDelete {
	mutation := newStoreMutation(c.config, OpDelete)
	return &StoreDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *StoreClient) DeleteOne(_m *Store) *StoreDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *StoreClient) DeleteOneID(id int64) *StoreDeleteOne {
	builder := c.Delete().Where(store.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &StoreDeleteOne{builder}
}

// Query returns a query builder for Store.
func (c *StoreClient) Query() *StoreQuery {
	return &StoreQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeStore},
		inters: c.Interceptors(),
	}
}

// Get returns a Store entity by its id.
func (c *StoreClient) Get(ctx context.Context, id int64) (*Store, error) {
	return c.Query().Where(store.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *StoreClient) GetX(ctx context.Context, id int64) *Store {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryFruitPrices queries the fruit_prices edge of a Store.
func (c *StoreClient) QueryFruitPrices(_m *Store) *StoreFruitPriceQuery {
	query := (&StoreFruitPriceClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(store.Table, store.FieldID, id),
			sqlgraph.To(storefruitprice.Table, storefruitprice.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, store.FruitPricesTable, store.FruitPricesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *StoreClient) Hooks() []Hook {
	return c.hooks.Store
}

// Interceptors returns the client interceptors.
func (c *StoreClient) Interceptors() []Interceptor {
	return c.inters.Store
}

func (c *StoreClient) mutate(ctx context.Context, m *StoreMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&StoreCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&StoreUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&StoreUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&StoreDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Store mutation op: %q", m.Op())
	}
}

// StoreFruitPriceClient is a client for the StoreFruitPrice schema.
type StoreFruitPriceClient struct {
	config
}

// NewStoreFruitPriceClient returns a client for the StoreFruitPrice from the given config.
func NewStoreFruitPriceClient(c config) *StoreFruitPriceClient {
	return &StoreFruitPriceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `storefruitprice.Hooks(f(g(h())))`.
func (c *StoreFruitPriceClient) Use(hooks ...Hook) {
	c.hooks.StoreFruitPrice = append(c.hooks.StoreFruitPrice, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `storefruitprice.Intercept(f(g(h())))`.
func (c *StoreFruitPriceClient) Intercept(interceptors ...Interceptor) {
	c.inters.StoreFruitPrice = append(c.inters.StoreFruitPrice, interceptors...)
}

// Create returns a builder for creating a StoreFruitPrice entity.
func (c *StoreFruitPriceClient) Create() *StoreFruitPriceCreate {
	mutation := newStoreFruitPriceMutation(c.config, OpCreate)
	return &StoreFruitPriceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of StoreFruitPrice entities.
func (c *StoreFruitPriceClient) CreateBulk(builders ...*StoreFruitPriceCreate) *StoreFruitPriceCreateBulk {
	return &StoreFruitPriceCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *StoreFruitPriceClient) MapCreateBulk(slice any, setFunc func(*StoreFruitPriceCreate, int)) *StoreFruitPriceCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &StoreFruitPriceCreateBulk{err: fmt.Errorf("calling to StoreFruitPriceClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*StoreFruitPriceCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &StoreFruitPriceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for StoreFruitPrice.
func (c *StoreFruitPriceClient) Update() *StoreFruitPriceUpdate {
	mutation := newStoreFruitPriceMutation(c.config, OpUpdate)
	return &StoreFruitPriceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *StoreFruitPriceClient) UpdateOne(_m *StoreFruitPrice) *StoreFruitPriceUpdateOne {
	mutation := newStoreFruitPriceMutation(c.config, OpUpdateOne, withStoreFruitPrice(_m))
	return &StoreFruitPriceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *StoreFruitPriceClient) UpdateOneID(id int64) *StoreFruitPriceUpdateOne {
	mutation := newStoreFruitPriceMutation(c.config, OpUpdateOne, withStoreFruitPriceID(id))
	return &StoreFruitPriceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for StoreFruitPrice.
func (c *StoreFruitPriceClient) Delete() *StoreFruitPriceDelete {
	mutation := newStoreFruitPriceMutation(c.config, OpDelete)
	return &StoreFruitPriceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *StoreFruitPriceClient) DeleteOne(_m *StoreFruitPrice) *StoreFruitPriceDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *StoreFruitPriceClient) DeleteOneID(id int64) *StoreFruitPriceDeleteOne {
	builder := c.Delete().Where(storefruitprice.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &StoreFruitPriceDeleteOne{builder}
}

// Query returns a query builder for StoreFruitPrice.
func (c *StoreFruitPriceClient) Query() *StoreFruitPriceQuery {
	return &StoreFruitPriceQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeStoreFruitPrice},
		inters: c.Interceptors(),
	}
}

// Get returns a StoreFruitPrice entity by its id.
func (c *StoreFruitPriceClient) Get(ctx context.Context, id int64) (*StoreFruitPrice, error) {
	return c.Query().Where(storefruitprice.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *StoreFruitPriceClient) GetX(ctx context.Context, id int64) *StoreFruitPrice {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryStore queries the store edge of a StoreFruitPrice.
func (c *StoreFruitPriceClient) QueryStore(_m *StoreFruitPrice) *StoreQuery {
	query := (&StoreClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(storefruitprice.Table, storefruitprice.FieldID, id),
			sqlgraph.To(store.Table, store.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, storefruitprice.StoreTable, storefruitprice.StoreColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *StoreFruitPriceClient) Hooks() []Hook {
	return c.hooks.StoreFruitPrice
}

// Interceptors returns the client interceptors.
func (c *StoreFruitPriceClient) Interceptors() []Interceptor {
	return c.inters.StoreFruitPrice
}

func (c *StoreFruitPriceClient) mutate(ctx context.Context, m *StoreFruitPriceMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&StoreFruitPriceCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&StoreFruitPriceUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&StoreFruitPriceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&StoreFruitPriceDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown StoreFruitPrice mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Fruit, Store, StoreFruitPrice []ent.Hook
	}
	inters struct {
		Fruit, Store, StoreFruitPrice []ent.Interceptor
	}
)
