// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/quarkusio/spring-quarkus-perf-comparison/golang/ent/fruit"
	"github.com/quarkusio/spring-quarkus-perf-comparison/golang/ent/predicate"
	"github.com/quarkusio/spring-quarkus-perf-comparison/golang/ent/store"
	"github.com/quarkusio/spring-quarkus-perf-comparison/golang/ent/storefruitprice"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeFruit           = "Fruit"
	TypeStore           = "Store"
	TypeStoreFruitPrice = "StoreFruitPrice"
)

// FruitMutation represents an operation that mutates the Fruit nodes in the graph.
type FruitMutation struct {
	config
	op            Op
	typ           string
	id            *int64
	name          *string
	description   *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Fruit, error)
	predicates    []predicate.Fruit
}

var _ ent.Mutation = (*FruitMutation)(nil)

// fruitOption allows management of the mutation configuration using functional options.
type fruitOption func(*FruitMutation)

// newFruitMutation creates new mutation for the Fruit entity.
func newFruitMutation(c config, op Op, opts ...fruitOption) *FruitMutation {
	m := &FruitMutation{
		config:        c,
		op:            op,
		typ:           TypeFruit,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withFruitID sets the ID field of the mutation.
func withFruitID(id int64) fruitOption {
	return func(m *FruitMutation) {
		var (
			err   error
			once  sync.Once
			value *Fruit
		)
		m.oldValue = func(ctx context.Context) (*Fruit, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Fruit.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withFruit sets the old Fruit of the mutation.
func withFruit(node *Fruit) fruitOption {
	return func(m *FruitMutation) {
		m.oldValue = func(context.Context) (*Fruit, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m FruitMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m FruitMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Fruit entities.
func (m *FruitMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *FruitMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *FruitMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Fruit.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *FruitMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *FruitMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Fruit entity.
// If the Fruit object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FruitMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *FruitMutation) ResetName() {
	m.name = nil
}

// SetDescription sets the "description" field.
func (m *FruitMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *FruitMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the Fruit entity.
// If the Fruit object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *FruitMutation) OldDescription(ctx context.Context) (v *string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ClearDescription clears the value of the "description" field.
func (m *FruitMutation) ClearDescription() {
	m.description = nil
	m.clearedFields[fruit.FieldDescription] = struct{}{}
}

// DescriptionCleared returns if the "description" field was cleared in this mutation.
func (m *FruitMutation) DescriptionCleared() bool {
	_, ok := m.clearedFields[fruit.FieldDescription]
	return ok
}

// ResetDescription resets all changes to the "description" field.
func (m *FruitMutation) ResetDescription() {
	m.description = nil
	delete(m.clearedFields, fruit.FieldDescription)
}

// Where appends a list predicates to the FruitMutation builder.
func (m *FruitMutation) Where(ps ...predicate.Fruit) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the FruitMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *FruitMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Fruit, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *FruitMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *FruitMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Fruit).
func (m *FruitMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *FruitMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.name != nil {
		fields = append(fields, fruit.FieldName)
	}
	if m.description != nil {
		fields = append(fields, fruit.FieldDescription)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *FruitMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case fruit.FieldName:
		return m.Name()
	case fruit.FieldDescription:
		return m.Description()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *FruitMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case fruit.FieldName:
		return m.OldName(ctx)
	case fruit.FieldDescription:
		return m.OldDescription(ctx)
	}
	return nil, fmt.Errorf("unknown Fruit field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *FruitMutation) SetField(name string, value ent.Value) error {
	switch name {
	case fruit.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case fruit.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	}
	return fmt.Errorf("unknown Fruit field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *FruitMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *FruitMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *FruitMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Fruit numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *FruitMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(fruit.FieldDescription) {
		fields = append(fields, fruit.FieldDescription)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *FruitMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *FruitMutation) ClearField(name string) error {
	switch name {
	case fruit.FieldDescription:
		m.ClearDescription()
		return nil
	}
	return fmt.Errorf("unknown Fruit nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *FruitMutation) ResetField(name string) error {
	switch name {
	case fruit.FieldName:
		m.ResetName()
		return nil
	case fruit.FieldDescription:
		m.ResetDescription()
		return nil
	}
	return fmt.Errorf("unknown Fruit field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *FruitMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *FruitMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *FruitMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *FruitMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *FruitMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *FruitMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *FruitMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Fruit unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *FruitMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Fruit edge %s", name)
}

// StoreMutation represents an operation that mutates the Store nodes in the graph.
type StoreMutation struct {
	config
	op                  Op
	typ                 string
	id                  *int64
	name                *string
	currency            *string
	address             *string
	city                *string
	country             *string
	clearedFields       map[string]struct{}
	fruit_prices        map[int64]struct{}
	removedfruit_prices map[int64]struct{}
	clearedfruit_prices bool
	done                bool
	oldValue            func(context.Context) (*Store, error)
	predicates          []predicate.Store
}

var _ ent.Mutation = (*StoreMutation)(nil)

// storeOption allows management of the mutation configuration using functional options.
type storeOption func(*StoreMutation)

// newStoreMutation creates new mutation for the Store entity.
func newStoreMutation(c config, op Op, opts ...storeOption) *StoreMutation {
	m := &StoreMutation{
		config:        c,
		op:            op,
		typ:           TypeStore,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withStoreID sets the ID field of the mutation.
func withStoreID(id int64) storeOption {
	return func(m *StoreMutation) {
		var (
			err   error
			once  sync.Once
			value *Store
		)
		m.oldValue = func(ctx context.Context) (*Store, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Store.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withStore sets the old Store of the mutation.
func withStore(node *Store) storeOption {
	return func(m *StoreMutation) {
		m.oldValue = func(context.Context) (*Store, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m StoreMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m StoreMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of Store entities.
func (m *StoreMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *StoreMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *StoreMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Store.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *StoreMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *StoreMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Store entity.
// If the Store object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *StoreMutation) ResetName() {
	m.name = nil
}

// SetCurrency sets the "currency" field.
func (m *StoreMutation) SetCurrency(s string) {
	m.currency = &s
}

// Currency returns the value of the "currency" field in the mutation.
func (m *StoreMutation) Currency() (r string, exists bool) {
	v := m.currency
	if v == nil {
		return
	}
	return *v, true
}

// OldCurrency returns the old "currency" field's value of the Store entity.
// If the Store object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreMutation) OldCurrency(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCurrency is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCurrency requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCurrency: %w", err)
	}
	return oldValue.Currency, nil
}

// ResetCurrency resets all changes to the "currency" field.
func (m *StoreMutation) ResetCurrency() {
	m.currency = nil
}

// SetAddress sets the "address" field.
func (m *StoreMutation) SetAddress(s string) {
	m.address = &s
}

// Address returns the value of the "address" field in the mutation.
func (m *StoreMutation) Address() (r string, exists bool) {
	v := m.address
	if v == nil {
		return
	}
	return *v, true
}

// OldAddress returns the old "address" field's value of the Store entity.
// If the Store object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreMutation) OldAddress(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAddress is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAddress requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAddress: %w", err)
	}
	return oldValue.Address, nil
}

// ResetAddress resets all changes to the "address" field.
func (m *StoreMutation) ResetAddress() {
	m.address = nil
}

// SetCity sets the "city" field.
func (m *StoreMutation) SetCity(s string) {
	m.city = &s
}

// City returns the value of the "city" field in the mutation.
func (m *StoreMutation) City() (r string, exists bool) {
	v := m.city
	if v == nil {
		return
	}
	return *v, true
}

// OldCity returns the old "city" field's value of the Store entity.
// If the Store object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreMutation) OldCity(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCity is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCity requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCity: %w", err)
	}
	return oldValue.City, nil
}

// ResetCity resets all changes to the "city" field.
func (m *StoreMutation) ResetCity() {
	m.city = nil
}

// SetCountry sets the "country" field.
func (m *StoreMutation) SetCountry(s string) {
	m.country = &s
}

// Country returns the value of the "country" field in the mutation.
func (m *StoreMutation) Country() (r string, exists bool) {
	v := m.country
	if v == nil {
		return
	}
	return *v, true
}

// OldCountry returns the old "country" field's value of the Store entity.
// If the Store object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreMutation) OldCountry(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCountry is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCountry requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCountry: %w", err)
	}
	return oldValue.Country, nil
}

// ResetCountry resets all changes to the "country" field.
func (m *StoreMutation) ResetCountry() {
	m.country = nil
}

// AddFruitPriceIDs adds the "fruit_prices" edge to the StoreFruitPrice entity by ids.
func (m *StoreMutation) AddFruitPriceIDs(ids ...int64) {
	if m.fruit_prices == nil {
		m.fruit_prices = make(map[int64]struct{})
	}
	for i := range ids {
		m.fruit_prices[ids[i]] = struct{}{}
	}
}

// ClearFruitPrices clears the "fruit_prices" edge to the StoreFruitPrice entity.
func (m *StoreMutation) ClearFruitPrices() {
	m.clearedfruit_prices = true
}

// FruitPricesCleared reports if the "fruit_prices" edge to the StoreFruitPrice entity was cleared.
func (m *StoreMutation) FruitPricesCleared() bool {
	return m.clearedfruit_prices
}

// RemoveFruitPriceIDs removes the "fruit_prices" edge to the StoreFruitPrice entity by IDs.
func (m *StoreMutation) RemoveFruitPriceIDs(ids ...int64) {
	if m.removedfruit_prices == nil {
		m.removedfruit_prices = make(map[int64]struct{})
	}
	for i := range ids {
		delete(m.fruit_prices, ids[i])
		m.removedfruit_prices[ids[i]] = struct{}{}
	}
}

// RemovedFruitPrices returns the removed IDs of the "fruit_prices" edge to the StoreFruitPrice entity.
func (m *StoreMutation) RemovedFruitPricesIDs() (ids []int64) {
	for id := range m.removedfruit_prices {
		ids = append(ids, id)
	}
	return
}

// FruitPricesIDs returns the "fruit_prices" edge IDs in the mutation.
func (m *StoreMutation) FruitPricesIDs() (ids []int64) {
	for id := range m.fruit_prices {
		ids = append(ids, id)
	}
	return
}

// ResetFruitPrices resets all changes to the "fruit_prices" edge.
func (m *StoreMutation) ResetFruitPrices() {
	m.fruit_prices = nil
	m.clearedfruit_prices = false
	m.removedfruit_prices = nil
}

// Where appends a list predicates to the StoreMutation builder.
func (m *StoreMutation) Where(ps ...predicate.Store) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the StoreMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *StoreMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Store, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *StoreMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *StoreMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Store).
func (m *StoreMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *StoreMutation) Fields() []string {
	fields := make([]string, 0, 5)
	if m.name != nil {
		fields = append(fields, store.FieldName)
	}
	if m.currency != nil {
		fields = append(fields, store.FieldCurrency)
	}
	if m.address != nil {
		fields = append(fields, store.FieldAddress)
	}
	if m.city != nil {
		fields = append(fields, store.FieldCity)
	}
	if m.country != nil {
		fields = append(fields, store.FieldCountry)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *StoreMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case store.FieldName:
		return m.Name()
	case store.FieldCurrency:
		return m.Currency()
	case store.FieldAddress:
		return m.Address()
	case store.FieldCity:
		return m.City()
	case store.FieldCountry:
		return m.Country()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *StoreMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case store.FieldName:
		return m.OldName(ctx)
	case store.FieldCurrency:
		return m.OldCurrency(ctx)
	case store.FieldAddress:
		return m.OldAddress(ctx)
	case store.FieldCity:
		return m.OldCity(ctx)
	case store.FieldCountry:
		return m.OldCountry(ctx)
	}
	return nil, fmt.Errorf("unknown Store field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *StoreMutation) SetField(name string, value ent.Value) error {
	switch name {
	case store.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case store.FieldCurrency:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCurrency(v)
		return nil
	case store.FieldAddress:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAddress(v)
		return nil
	case store.FieldCity:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCity(v)
		return nil
	case store.FieldCountry:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCountry(v)
		return nil
	}
	return fmt.Errorf("unknown Store field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *StoreMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *StoreMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *StoreMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Store numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *StoreMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *StoreMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *StoreMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Store nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *StoreMutation) ResetField(name string) error {
	switch name {
	case store.FieldName:
		m.ResetName()
		return nil
	case store.FieldCurrency:
		m.ResetCurrency()
		return nil
	case store.FieldAddress:
		m.ResetAddress()
		return nil
	case store.FieldCity:
		m.ResetCity()
		return nil
	case store.FieldCountry:
		m.ResetCountry()
		return nil
	}
	return fmt.Errorf("unknown Store field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *StoreMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.fruit_prices != nil {
		edges = append(edges, store.EdgeFruitPrices)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *StoreMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case store.EdgeFruitPrices:
		ids := make([]ent.Value, 0, len(m.fruit_prices))
		for id := range m.fruit_prices {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *StoreMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	if m.removedfruit_prices != nil {
		edges = append(edges, store.EdgeFruitPrices)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *StoreMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case store.EdgeFruitPrices:
		ids := make([]ent.Value, 0, len(m.removedfruit_prices))
		for id := range m.removedfruit_prices {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *StoreMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedfruit_prices {
		edges = append(edges, store.EdgeFruitPrices)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *StoreMutation) EdgeCleared(name string) bool {
	switch name {
	case store.EdgeFruitPrices:
		return m.clearedfruit_prices
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *StoreMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Store unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *StoreMutation) ResetEdge(name string) error {
	switch name {
	case store.EdgeFruitPrices:
		m.ResetFruitPrices()
		return nil
	}
	return fmt.Errorf("unknown Store edge %s", name)
}

// StoreFruitPriceMutation represents an operation that mutates the StoreFruitPrice nodes in the graph.
type StoreFruitPriceMutation struct {
	config
	op            Op
	typ           string
	id            *int64
	price         *float64
	addprice      *float64
	clearedFields map[string]struct{}
	store         *int64
	clearedstore  bool
	done          bool
	oldValue      func(context.Context) (*StoreFruitPrice, error)
	predicates    []predicate.StoreFruitPrice
}

var _ ent.Mutation = (*StoreFruitPriceMutation)(nil)

// storefruitpriceOption allows management of the mutation configuration using functional options.
type storefruitpriceOption func(*StoreFruitPriceMutation)

// newStoreFruitPriceMutation creates new mutation for the StoreFruitPrice entity.
func newStoreFruitPriceMutation(c config, op Op, opts ...storefruitpriceOption) *StoreFruitPriceMutation {
	m := &StoreFruitPriceMutation{
		config:        c,
		op:            op,
		typ:           TypeStoreFruitPrice,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withStoreFruitPriceID sets the ID field of the mutation.
func withStoreFruitPriceID(id int64) storefruitpriceOption {
	return func(m *StoreFruitPriceMutation) {
		var (
			err   error
			once  sync.Once
			value *StoreFruitPrice
		)
		m.oldValue = func(ctx context.Context) (*StoreFruitPrice, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().StoreFruitPrice.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withStoreFruitPrice sets the old StoreFruitPrice of the mutation.
func withStoreFruitPrice(node *StoreFruitPrice) storefruitpriceOption {
	return func(m *StoreFruitPriceMutation) {
		m.oldValue = func(context.Context) (*StoreFruitPrice, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m StoreFruitPriceMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m StoreFruitPriceMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of StoreFruitPrice entities.
func (m *StoreFruitPriceMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *StoreFruitPriceMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *StoreFruitPriceMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().StoreFruitPrice.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetStoreID sets the "store_id" field.
func (m *StoreFruitPriceMutation) SetStoreID(i int64) {
	m.store = &i
}

// StoreID returns the value of the "store_id" field in the mutation.
func (m *StoreFruitPriceMutation) StoreID() (r int64, exists bool) {
	v := m.store
	if v == nil {
		return
	}
	return *v, true
}

// OldStoreID returns the old "store_id" field's value of the StoreFruitPrice entity.
// If the StoreFruitPrice object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreFruitPriceMutation) OldStoreID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStoreID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStoreID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStoreID: %w", err)
	}
	return oldValue.StoreID, nil
}

// ResetStoreID resets all changes to the "store_id" field.
func (m *StoreFruitPriceMutation) ResetStoreID() {
	m.store = nil
}

// SetPrice sets the "price" field.
func (m *StoreFruitPriceMutation) SetPrice(f float64) {
	m.price = &f
	m.addprice = nil
}

// Price returns the value of the "price" field in the mutation.
func (m *StoreFruitPriceMutation) Price() (r float64, exists bool) {
	v := m.price
	if v == nil {
		return
	}
	return *v, true
}

// OldPrice returns the old "price" field's value of the StoreFruitPrice entity.
// If the StoreFruitPrice object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *StoreFruitPriceMutation) OldPrice(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldPrice is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldPrice requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldPrice: %w", err)
	}
	return oldValue.Price, nil
}

// AddPrice adds f to the "price" field.
func (m *StoreFruitPriceMutation) AddPrice(f float64) {
	if m.addprice != nil {
		*m.addprice += f
	} else {
		m.addprice = &f
	}
}

// AddedPrice returns the value that was added to the "price" field in this mutation.
func (m *StoreFruitPriceMutation) AddedPrice() (r float64, exists bool) {
	v := m.addprice
	if v == nil {
		return
	}
	return *v, true
}

// ResetPrice resets all changes to the "price" field.
func (m *StoreFruitPriceMutation) ResetPrice() {
	m.price = nil
	m.addprice = nil
}

// ClearStore clears the "store" edge to the Store entity.
func (m *StoreFruitPriceMutation) ClearStore() {
	m.clearedstore = true
	m.clearedFields[storefruitprice.FieldStoreID] = struct{}{}
}

// StoreCleared reports if the "store" edge to the Store entity was cleared.
func (m *StoreFruitPriceMutation) StoreCleared() bool {
	return m.clearedstore
}

// StoreIDs returns the "store" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// StoreID instead. It exists only for internal usage by the builders.
func (m *StoreFruitPriceMutation) StoreIDs() (ids []int64) {
	if id := m.store; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetStore resets all changes to the "store" edge.
func (m *StoreFruitPriceMutation) ResetStore() {
	m.store = nil
	m.clearedstore = false
}

// Where appends a list predicates to the StoreFruitPriceMutation builder.
func (m *StoreFruitPriceMutation) Where(ps ...predicate.StoreFruitPrice) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the StoreFruitPriceMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *StoreFruitPriceMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.StoreFruitPrice, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *StoreFruitPriceMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *StoreFruitPriceMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (StoreFruitPrice).
func (m *StoreFruitPriceMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *StoreFruitPriceMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.store != nil {
		fields = append(fields, storefruitprice.FieldStoreID)
	}
	if m.price != nil {
		fields = append(fields, storefruitprice.FieldPrice)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *StoreFruitPriceMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case storefruitprice.FieldStoreID:
		return m.StoreID()
	case storefruitprice.FieldPrice:
		return m.Price()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *StoreFruitPriceMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case storefruitprice.FieldStoreID:
		return m.OldStoreID(ctx)
	case storefruitprice.FieldPrice:
		return m.OldPrice(ctx)
	}
	return nil, fmt.Errorf("unknown StoreFruitPrice field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *StoreFruitPriceMutation) SetField(name string, value ent.Value) error {
	switch name {
	case storefruitprice.FieldStoreID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStoreID(v)
		return nil
	case storefruitprice.FieldPrice:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetPrice(v)
		return nil
	}
	return fmt.Errorf("unknown StoreFruitPrice field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *StoreFruitPriceMutation) AddedFields() []string {
	var fields []string
	if m.addprice != nil {
		fields = append(fields, storefruitprice.FieldPrice)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *StoreFruitPriceMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case storefruitprice.FieldPrice:
		return m.AddedPrice()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *StoreFruitPriceMutation) AddField(name string, value ent.Value) error {
	switch name {
	case storefruitprice.FieldPrice:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddPrice(v)
		return nil
	}
	return fmt.Errorf("unknown StoreFruitPrice numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *StoreFruitPriceMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *StoreFruitPriceMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *StoreFruitPriceMutation) ClearField(name string) error {
	return fmt.Errorf("unknown StoreFruitPrice nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *StoreFruitPriceMutation) ResetField(name string) error {
	switch name {
	case storefruitprice.FieldStoreID:
		m.ResetStoreID()
		return nil
	case storefruitprice.FieldPrice:
		m.ResetPrice()
		return nil
	}
	return fmt.Errorf("unknown StoreFruitPrice field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *StoreFruitPriceMutation) AddedEdges() []string {
	edges := make([]string, 0, 1)
	if m.store != nil {
		edges = append(edges, storefruitprice.EdgeStore)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *StoreFruitPriceMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case storefruitprice.EdgeStore:
		if id := m.store; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *StoreFruitPriceMutation) RemovedEdges() []string {
	edges := make([]string, 0, 1)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *StoreFruitPriceMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *StoreFruitPriceMutation) ClearedEdges() []string {
	edges := make([]string, 0, 1)
	if m.clearedstore {
		edges = append(edges, storefruitprice.EdgeStore)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *StoreFruitPriceMutation) EdgeCleared(name string) bool {
	switch name {
	case storefruitprice.EdgeStore:
		return m.clearedstore
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *StoreFruitPriceMutation) ClearEdge(name string) error {
	switch name {
	case storefruitprice.EdgeStore:
		m.ClearStore()
		return nil
	}
	return fmt.Errorf("unknown StoreFruitPrice unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *StoreFruitPriceMutation) ResetEdge(name string) error {
	switch name {
	case storefruitprice.EdgeStore:
		m.ResetStore()
		return nil
	}
	return fmt.Errorf("unknown StoreFruitPrice edge %s", name)
}
