// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/quarkusio/spring-quarkus-perf-comparison/golang/ent/fruit"
	"github.com/quarkusio/spring-quarkus-perf-comparison/golang/ent/schema"
	"github.com/quarkusio/spring-quarkus-perf-comparison/golang/ent/store"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	fruitFields := schema.Fruit{}.Fields()
	_ = fruitFields
	// fruitDescName is the schema descriptor for name field.
	fruitDescName := fruitFields[1].Descriptor()
	// fruit.NameValidator is a validator for the "name" field. It is called by the builders before save.
	fruit.NameValidator = fruitDescName.Validators[0].(func(string) error)
	storeFields := schema.Store{}.Fields()
	_ = storeFields
	// storeDescName is the schema descriptor for name field.
	storeDescName := storeFields[1].Descriptor()
	// store.NameValidator is a validator for the "name" field. It is called by the builders before save.
	store.NameValidator = storeDescName.Validators[0].(func(string) error)
	// storeDescCurrency is the schema descriptor for currency field.
	storeDescCurrency := storeFields[2].Descriptor()
	// store.CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	store.CurrencyValidator = storeDescCurrency.Validators[0].(func(string) error)
	// storeDescAddress is the schema descriptor for address field.
	storeDescAddress := storeFields[3].Descriptor()
	// store.AddressValidator is a validator for the "address" field. It is called by the builders before save.
	store.AddressValidator = storeDescAddress.Validators[0].(func(string) error)
	// storeDescCity is the schema descriptor for city field.
	storeDescCity := storeFields[4].Descriptor()
	// store.CityValidator is a validator for the "city" field. It is called by the builders before save.
	store.CityValidator = storeDescCity.Validators[0].(func(string) error)
	// storeDescCountry is the schema descriptor for country field.
	storeDescCountry := storeFields[5].Descriptor()
	// store.CountryValidator is a validator for the "country" field. It is called by the builders before save.
	store.CountryValidator = storeDescCountry.Validators[0].(func(string) error)
}
