// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/quarkusio/spring-quarkus-perf-comparison/golang/ent/store"
	"github.com/quarkusio/spring-quarkus-perf-comparison/golang/ent/storefruitprice"
)

// StoreFruitPrice is the model entity for the StoreFruitPrice schema.
type StoreFruitPrice struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// StoreID holds the value of the "store_id" field.
	StoreID int64 `json:"store_id,omitempty"`
	// Price holds the value of the "price" field.
	Price float64 `json:"price,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StoreFruitPriceQuery when eager-loading is set.
	Edges        StoreFruitPriceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// StoreFruitPriceEdges holds the relations/edges for other nodes in the graph.
type StoreFruitPriceEdges struct {
	// Store holds the value of the store edge.
	Store *Store `json:"store,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// StoreOrErr returns the Store value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e StoreFruitPriceEdges) StoreOrErr() (*Store, error) {
	if e.Store != nil {
		return e.Store, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: store.Label}
	}
	return nil, &NotLoadedError{edge: "store"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StoreFruitPrice) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case storefruitprice.FieldPrice:
			values[i] = new(sql.NullFloat64)
		case storefruitprice.FieldID, storefruitprice.FieldStoreID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StoreFruitPrice fields.
func (_m *StoreFruitPrice) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case storefruitprice.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case storefruitprice.FieldStoreID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field store_id", values[i])
			} else if value.Valid {
				_m.StoreID = value.Int64
			}
		case storefruitprice.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				_m.Price = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the StoreFruitPrice.
// This includes values selected through modifiers, order, etc.
func (_m *StoreFruitPrice) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryStore queries the "store" edge of the StoreFruitPrice entity.
func (_m *StoreFruitPrice) QueryStore() *StoreQuery {
	return NewStoreFruitPriceClient(_m.config).QueryStore(_m)
}

// Update returns a builder for updating this StoreFruitPrice.
// Note that you need to call StoreFruitPrice.Unwrap() before calling this method if this StoreFruitPrice
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *StoreFruitPrice) Update() *StoreFruitPriceUpdateOne {
	return NewStoreFruitPriceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the StoreFruitPrice entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *StoreFruitPrice) Unwrap() *StoreFruitPrice {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: StoreFruitPrice is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *StoreFruitPrice) String() string {
	var builder strings.Builder
	builder.WriteString("StoreFruitPrice(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("store_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.StoreID))
	builder.WriteString(", ")
	builder.WriteString("price=")
	builder.WriteString(fmt.Sprintf("%v", _m.Price))
	builder.WriteByte(')')
	return builder.String()
}

// StoreFruitPrices is a parsable slice of StoreFruitPrice.
type StoreFruitPrices []*StoreFruitPrice
