// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/quarkusio/spring-quarkus-perf-comparison/golang/ent/store"
	"github.com/quarkusio/spring-quarkus-perf-comparison/golang/ent/storefruitprice"
)

// StoreCreate is the builder for creating a Store entity.
type StoreCreate struct {
	config
	mutation *StoreMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *StoreCreate) SetName(v string) *StoreCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *StoreCreate) SetCurrency(v string) *StoreCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetAddress sets the "address" field.
func (_c *StoreCreate) SetAddress(v string) *StoreCreate {
	_c.mutation.SetAddress(v)
	return _c
}

// SetCity sets the "city" field.
func (_c *StoreCreate) SetCity(v string) *StoreCreate {
	_c.mutation.SetCity(v)
	return _c
}

// SetCountry sets the "country" field.
func (_c *StoreCreate) SetCountry(v string) *StoreCreate {
	_c.mutation.SetCountry(v)
	return _c
}

// SetID sets the "id" field.
func (_c *StoreCreate) SetID(v int64) *StoreCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddFruitPriceIDs adds the "fruit_prices" edge to the StoreFruitPrice entity by IDs.
func (_c *StoreCreate) AddFruitPriceIDs(ids ...int64) *StoreCreate {
	_c.mutation.AddFruitPriceIDs(ids...)
	return _c
}

// AddFruitPrices adds the "fruit_prices" edges to the StoreFruitPrice entity.
func (_c *StoreCreate) AddFruitPrices(v ...*StoreFruitPrice) *StoreCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFruitPriceIDs(ids...)
}

// Mutation returns the StoreMutation object of the builder.
func (_c *StoreCreate) Mutation() *StoreMutation {
	return _c.mutation
}

// Save creates the Store in the database.
func (_c *StoreCreate) Save(ctx context.Context) (*Store, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StoreCreate) SaveX(ctx context.Context) *Store {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StoreCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StoreCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StoreCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Store.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := store.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Store.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "Store.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := store.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Store.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "Store.address"`)}
	}
	if v, ok := _c.mutation.Address(); ok {
		if err := store.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Store.address": %w`, err)}
		}
	}
	if _, ok := _c.mutation.City(); !ok {
		return &ValidationError{Name: "city", err: errors.New(`ent: missing required field "Store.city"`)}
	}
	if v, ok := _c.mutation.City(); ok {
		if err := store.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Store.city": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Country(); !ok {
		return &ValidationError{Name: "country", err: errors.New(`ent: missing required field "Store.country"`)}
	}
	if v, ok := _c.mutation.Country(); ok {
		if err := store.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "Store.country": %w`, err)}
		}
	}
	return nil
}

func (_c *StoreCreate) sqlSave(ctx context.Context) (*Store, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StoreCreate) createSpec() (*Store, *sqlgraph.CreateSpec) {
	var (
		_node = &Store{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(store.Table, sqlgraph.NewFieldSpec(store.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(store.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(store.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.Address(); ok {
		_spec.SetField(store.FieldAddress, field.TypeString, value)
		_node.Address = value
	}
	if value, ok := _c.mutation.City(); ok {
		_spec.SetField(store.FieldCity, field.TypeString, value)
		_node.City = value
	}
	if value, ok := _c.mutation.Country(); ok {
		_spec.SetField(store.FieldCountry, field.TypeString, value)
		_node.Country = value
	}
	if nodes := _c.mutation.FruitPricesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   store.FruitPricesTable,
			Columns: []string{store.FruitPricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storefruitprice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// StoreCreateBulk is the builder for creating many Store entities in bulk.
type StoreCreateBulk struct {
	config
	err      error
	builders []*StoreCreate
}

// Save creates the Store entities in the database.
func (_c *StoreCreateBulk) Save(ctx context.Context) ([]*Store, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Store, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StoreMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StoreCreateBulk) SaveX(ctx context.Context) []*Store {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StoreCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StoreCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
