// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/quarkusio/spring-quarkus-perf-comparison/golang/ent/predicate"
	"github.com/quarkusio/spring-quarkus-perf-comparison/golang/ent/store"
	"github.com/quarkusio/spring-quarkus-perf-comparison/golang/ent/storefruitprice"
)

// StoreUpdate is the builder for updating Store entities.
type StoreUpdate struct {
	config
	hooks    []Hook
	mutation *StoreMutation
}

// Where appends a list predicates to the StoreUpdate builder.
func (_u *StoreUpdate) Where(ps ...predicate.Store) *StoreUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *StoreUpdate) SetName(v string) *StoreUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StoreUpdate) SetNillableName(v *string) *StoreUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *StoreUpdate) SetCurrency(v string) *StoreUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *StoreUpdate) SetNillableCurrency(v *string) *StoreUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *StoreUpdate) SetAddress(v string) *StoreUpdate {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *StoreUpdate) SetNillableAddress(v *string) *StoreUpdate {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetCity sets the "city" field.
func (_u *StoreUpdate) SetCity(v string) *StoreUpdate {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *StoreUpdate) SetNillableCity(v *string) *StoreUpdate {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// SetCountry sets the "country" field.
func (_u *StoreUpdate) SetCountry(v string) *StoreUpdate {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *StoreUpdate) SetNillableCountry(v *string) *StoreUpdate {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// AddFruitPriceIDs adds the "fruit_prices" edge to the StoreFruitPrice entity by IDs.
func (_u *StoreUpdate) AddFruitPriceIDs(ids ...int64) *StoreUpdate {
	_u.mutation.AddFruitPriceIDs(ids...)
	return _u
}

// AddFruitPrices adds the "fruit_prices" edges to the StoreFruitPrice entity.
func (_u *StoreUpdate) AddFruitPrices(v ...*StoreFruitPrice) *StoreUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFruitPriceIDs(ids...)
}

// Mutation returns the StoreMutation object of the builder.
func (_u *StoreUpdate) Mutation() *StoreMutation {
	return _u.mutation
}

// ClearFruitPrices clears all "fruit_prices" edges to the StoreFruitPrice entity.
func (_u *StoreUpdate) ClearFruitPrices() *StoreUpdate {
	_u.mutation.ClearFruitPrices()
	return _u
}

// RemoveFruitPriceIDs removes the "fruit_prices" edge to StoreFruitPrice entities by IDs.
func (_u *StoreUpdate) RemoveFruitPriceIDs(ids ...int64) *StoreUpdate {
	_u.mutation.RemoveFruitPriceIDs(ids...)
	return _u
}

// RemoveFruitPrices removes "fruit_prices" edges to StoreFruitPrice entities.
func (_u *StoreUpdate) RemoveFruitPrices(v ...*StoreFruitPrice) *StoreUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFruitPriceIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StoreUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StoreUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StoreUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StoreUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StoreUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := store.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Store.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := store.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Store.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := store.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Store.address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.City(); ok {
		if err := store.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Store.city": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Country(); ok {
		if err := store.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "Store.country": %w`, err)}
		}
	}
	return nil
}

func (_u *StoreUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(store.Table, store.Columns, sqlgraph.NewFieldSpec(store.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(store.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(store.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(store.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(store.FieldCity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(store.FieldCountry, field.TypeString, value)
	}
	if _u.mutation.FruitPricesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   store.FruitPricesTable,
			Columns: []string{store.FruitPricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storefruitprice.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFruitPricesIDs(); len(nodes) > 0 && !_u.mutation.FruitPricesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   store.FruitPricesTable,
			Columns: []string{store.FruitPricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storefruitprice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FruitPricesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   store.FruitPricesTable,
			Columns: []string{store.FruitPricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storefruitprice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{store.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StoreUpdateOne is the builder for updating a single Store entity.
type StoreUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StoreMutation
}

// SetName sets the "name" field.
func (_u *StoreUpdateOne) SetName(v string) *StoreUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *StoreUpdateOne) SetNillableName(v *string) *StoreUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *StoreUpdateOne) SetCurrency(v string) *StoreUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *StoreUpdateOne) SetNillableCurrency(v *string) *StoreUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetAddress sets the "address" field.
func (_u *StoreUpdateOne) SetAddress(v string) *StoreUpdateOne {
	_u.mutation.SetAddress(v)
	return _u
}

// SetNillableAddress sets the "address" field if the given value is not nil.
func (_u *StoreUpdateOne) SetNillableAddress(v *string) *StoreUpdateOne {
	if v != nil {
		_u.SetAddress(*v)
	}
	return _u
}

// SetCity sets the "city" field.
func (_u *StoreUpdateOne) SetCity(v string) *StoreUpdateOne {
	_u.mutation.SetCity(v)
	return _u
}

// SetNillableCity sets the "city" field if the given value is not nil.
func (_u *StoreUpdateOne) SetNillableCity(v *string) *StoreUpdateOne {
	if v != nil {
		_u.SetCity(*v)
	}
	return _u
}

// SetCountry sets the "country" field.
func (_u *StoreUpdateOne) SetCountry(v string) *StoreUpdateOne {
	_u.mutation.SetCountry(v)
	return _u
}

// SetNillableCountry sets the "country" field if the given value is not nil.
func (_u *StoreUpdateOne) SetNillableCountry(v *string) *StoreUpdateOne {
	if v != nil {
		_u.SetCountry(*v)
	}
	return _u
}

// AddFruitPriceIDs adds the "fruit_prices" edge to the StoreFruitPrice entity by IDs.
func (_u *StoreUpdateOne) AddFruitPriceIDs(ids ...int64) *StoreUpdateOne {
	_u.mutation.AddFruitPriceIDs(ids...)
	return _u
}

// AddFruitPrices adds the "fruit_prices" edges to the StoreFruitPrice entity.
func (_u *StoreUpdateOne) AddFruitPrices(v ...*StoreFruitPrice) *StoreUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFruitPriceIDs(ids...)
}

// Mutation returns the StoreMutation object of the builder.
func (_u *StoreUpdateOne) Mutation() *StoreMutation {
	return _u.mutation
}

// ClearFruitPrices clears all "fruit_prices" edges to the StoreFruitPrice entity.
func (_u *StoreUpdateOne) ClearFruitPrices() *StoreUpdateOne {
	_u.mutation.ClearFruitPrices()
	return _u
}

// RemoveFruitPriceIDs removes the "fruit_prices" edge to StoreFruitPrice entities by IDs.
func (_u *StoreUpdateOne) RemoveFruitPriceIDs(ids ...int64) *StoreUpdateOne {
	_u.mutation.RemoveFruitPriceIDs(ids...)
	return _u
}

// RemoveFruitPrices removes "fruit_prices" edges to StoreFruitPrice entities.
func (_u *StoreUpdateOne) RemoveFruitPrices(v ...*StoreFruitPrice) *StoreUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFruitPriceIDs(ids...)
}

// Where appends a list predicates to the StoreUpdate builder.
func (_u *StoreUpdateOne) Where(ps ...predicate.Store) *StoreUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StoreUpdateOne) Select(field string, fields ...string) *StoreUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Store entity.
func (_u *StoreUpdateOne) Save(ctx context.Context) (*Store, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StoreUpdateOne) SaveX(ctx context.Context) *Store {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StoreUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StoreUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StoreUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := store.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Store.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := store.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "Store.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Address(); ok {
		if err := store.AddressValidator(v); err != nil {
			return &ValidationError{Name: "address", err: fmt.Errorf(`ent: validator failed for field "Store.address": %w`, err)}
		}
	}
	if v, ok := _u.mutation.City(); ok {
		if err := store.CityValidator(v); err != nil {
			return &ValidationError{Name: "city", err: fmt.Errorf(`ent: validator failed for field "Store.city": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Country(); ok {
		if err := store.CountryValidator(v); err != nil {
			return &ValidationError{Name: "country", err: fmt.Errorf(`ent: validator failed for field "Store.country": %w`, err)}
		}
	}
	return nil
}

func (_u *StoreUpdateOne) sqlSave(ctx context.Context) (_node *Store, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(store.Table, store.Columns, sqlgraph.NewFieldSpec(store.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Store.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, store.FieldID)
		for _, f := range fields {
			if !store.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != store.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(store.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(store.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Address(); ok {
		_spec.SetField(store.FieldAddress, field.TypeString, value)
	}
	if value, ok := _u.mutation.City(); ok {
		_spec.SetField(store.FieldCity, field.TypeString, value)
	}
	if value, ok := _u.mutation.Country(); ok {
		_spec.SetField(store.FieldCountry, field.TypeString, value)
	}
	if _u.mutation.FruitPricesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   store.FruitPricesTable,
			Columns: []string{store.FruitPricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storefruitprice.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFruitPricesIDs(); len(nodes) > 0 && !_u.mutation.FruitPricesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   store.FruitPricesTable,
			Columns: []string{store.FruitPricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storefruitprice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FruitPricesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   store.FruitPricesTable,
			Columns: []string{store.FruitPricesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storefruitprice.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Store{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{store.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
