// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/quarkusio/spring-quarkus-perf-comparison/golang/ent/store"
	"github.com/quarkusio/spring-quarkus-perf-comparison/golang/ent/storefruitprice"
)

// StoreFruitPriceCreate is the builder for creating a StoreFruitPrice entity.
type StoreFruitPriceCreate struct {
	config
	mutation *StoreFruitPriceMutation
	hooks    []Hook
}

// SetStoreID sets the "store_id" field.
func (_c *StoreFruitPriceCreate) SetStoreID(v int64) *StoreFruitPriceCreate {
	_c.mutation.SetStoreID(v)
	return _c
}

// SetPrice sets the "price" field.
func (_c *StoreFruitPriceCreate) SetPrice(v float64) *StoreFruitPriceCreate {
	_c.mutation.SetPrice(v)
	return _c
}

// SetID sets the "id" field.
func (_c *StoreFruitPriceCreate) SetID(v int64) *StoreFruitPriceCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetStore sets the "store" edge to the Store entity.
func (_c *StoreFruitPriceCreate) SetStore(v *Store) *StoreFruitPriceCreate {
	return _c.SetStoreID(v.ID)
}

// Mutation returns the StoreFruitPriceMutation object of the builder.
func (_c *StoreFruitPriceCreate) Mutation() *StoreFruitPriceMutation {
	return _c.mutation
}

// Save creates the StoreFruitPrice in the database.
func (_c *StoreFruitPriceCreate) Save(ctx context.Context) (*StoreFruitPrice, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StoreFruitPriceCreate) SaveX(ctx context.Context) *StoreFruitPrice {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StoreFruitPriceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StoreFruitPriceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StoreFruitPriceCreate) check() error {
	if _, ok := _c.mutation.StoreID(); !ok {
		return &ValidationError{Name: "store_id", err: errors.New(`ent: missing required field "StoreFruitPrice.store_id"`)}
	}
	if _, ok := _c.mutation.Price(); !ok {
		return &ValidationError{Name: "price", err: errors.New(`ent: missing required field "StoreFruitPrice.price"`)}
	}
	if len(_c.mutation.StoreIDs()) == 0 {
		return &ValidationError{Name: "store", err: errors.New(`ent: missing required edge "StoreFruitPrice.store"`)}
	}
	return nil
}

func (_c *StoreFruitPriceCreate) sqlSave(ctx context.Context) (*StoreFruitPrice, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StoreFruitPriceCreate) createSpec() (*StoreFruitPrice, *sqlgraph.CreateSpec) {
	var (
		_node = &StoreFruitPrice{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(storefruitprice.Table, sqlgraph.NewFieldSpec(storefruitprice.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Price(); ok {
		_spec.SetField(storefruitprice.FieldPrice, field.TypeFloat64, value)
		_node.Price = value
	}
	if nodes := _c.mutation.StoreIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   storefruitprice.StoreTable,
			Columns: []string{storefruitprice.StoreColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(store.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.StoreID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// StoreFruitPriceCreateBulk is the builder for creating many StoreFruitPrice entities in bulk.
type StoreFruitPriceCreateBulk struct {
	config
	err      error
	builders []*StoreFruitPriceCreate
}

// Save creates the StoreFruitPrice entities in the database.
func (_c *StoreFruitPriceCreateBulk) Save(ctx context.Context) ([]*StoreFruitPrice, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*StoreFruitPrice, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StoreFruitPriceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StoreFruitPriceCreateBulk) SaveX(ctx context.Context) []*StoreFruitPrice {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StoreFruitPriceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StoreFruitPriceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
