// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/quarkusio/spring-quarkus-perf-comparison/golang/ent/predicate"
	"github.com/quarkusio/spring-quarkus-perf-comparison/golang/ent/store"
	"github.com/quarkusio/spring-quarkus-perf-comparison/golang/ent/storefruitprice"
)

// StoreFruitPriceUpdate is the builder for updating StoreFruitPrice entities.
type StoreFruitPriceUpdate struct {
	config
	hooks    []Hook
	mutation *StoreFruitPriceMutation
}

// Where appends a list predicates to the StoreFruitPriceUpdate builder.
func (_u *StoreFruitPriceUpdate) Where(ps ...predicate.StoreFruitPrice) *StoreFruitPriceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStoreID sets the "store_id" field.
func (_u *StoreFruitPriceUpdate) SetStoreID(v int64) *StoreFruitPriceUpdate {
	_u.mutation.SetStoreID(v)
	return _u
}

// SetNillableStoreID sets the "store_id" field if the given value is not nil.
func (_u *StoreFruitPriceUpdate) SetNillableStoreID(v *int64) *StoreFruitPriceUpdate {
	if v != nil {
		_u.SetStoreID(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *StoreFruitPriceUpdate) SetPrice(v float64) *StoreFruitPriceUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *StoreFruitPriceUpdate) SetNillablePrice(v *float64) *StoreFruitPriceUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *StoreFruitPriceUpdate) AddPrice(v float64) *StoreFruitPriceUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetStore sets the "store" edge to the Store entity.
func (_u *StoreFruitPriceUpdate) SetStore(v *Store) *StoreFruitPriceUpdate {
	return _u.SetStoreID(v.ID)
}

// Mutation returns the StoreFruitPriceMutation object of the builder.
func (_u *StoreFruitPriceUpdate) Mutation() *StoreFruitPriceMutation {
	return _u.mutation
}

// ClearStore clears the "store" edge to the Store entity.
func (_u *StoreFruitPriceUpdate) ClearStore() *StoreFruitPriceUpdate {
	_u.mutation.ClearStore()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StoreFruitPriceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StoreFruitPriceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StoreFruitPriceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StoreFruitPriceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StoreFruitPriceUpdate) check() error {
	if _u.mutation.StoreCleared() && len(_u.mutation.StoreIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "StoreFruitPrice.store"`)
	}
	return nil
}

func (_u *StoreFruitPriceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(storefruitprice.Table, storefruitprice.Columns, sqlgraph.NewFieldSpec(storefruitprice.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(storefruitprice.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(storefruitprice.FieldPrice, field.TypeFloat64, value)
	}
	if _u.mutation.StoreCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   storefruitprice.StoreTable,
			Columns: []string{storefruitprice.StoreColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(store.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StoreIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   storefruitprice.StoreTable,
			Columns: []string{storefruitprice.StoreColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(store.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{storefruitprice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StoreFruitPriceUpdateOne is the builder for updating a single StoreFruitPrice entity.
type StoreFruitPriceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StoreFruitPriceMutation
}

// SetStoreID sets the "store_id" field.
func (_u *StoreFruitPriceUpdateOne) SetStoreID(v int64) *StoreFruitPriceUpdateOne {
	_u.mutation.SetStoreID(v)
	return _u
}

// SetNillableStoreID sets the "store_id" field if the given value is not nil.
func (_u *StoreFruitPriceUpdateOne) SetNillableStoreID(v *int64) *StoreFruitPriceUpdateOne {
	if v != nil {
		_u.SetStoreID(*v)
	}
	return _u
}

// SetPrice sets the "price" field.
func (_u *StoreFruitPriceUpdateOne) SetPrice(v float64) *StoreFruitPriceUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *StoreFruitPriceUpdateOne) SetNillablePrice(v *float64) *StoreFruitPriceUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *StoreFruitPriceUpdateOne) AddPrice(v float64) *StoreFruitPriceUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetStore sets the "store" edge to the Store entity.
func (_u *StoreFruitPriceUpdateOne) SetStore(v *Store) *StoreFruitPriceUpdateOne {
	return _u.SetStoreID(v.ID)
}

// Mutation returns the StoreFruitPriceMutation object of the builder.
func (_u *StoreFruitPriceUpdateOne) Mutation() *StoreFruitPriceMutation {
	return _u.mutation
}

// ClearStore clears the "store" edge to the Store entity.
func (_u *StoreFruitPriceUpdateOne) ClearStore() *StoreFruitPriceUpdateOne {
	_u.mutation.ClearStore()
	return _u
}

// Where appends a list predicates to the StoreFruitPriceUpdate builder.
func (_u *StoreFruitPriceUpdateOne) Where(ps ...predicate.StoreFruitPrice) *StoreFruitPriceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StoreFruitPriceUpdateOne) Select(field string, fields ...string) *StoreFruitPriceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated StoreFruitPrice entity.
func (_u *StoreFruitPriceUpdateOne) Save(ctx context.Context) (*StoreFruitPrice, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StoreFruitPriceUpdateOne) SaveX(ctx context.Context) *StoreFruitPrice {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StoreFruitPriceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StoreFruitPriceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StoreFruitPriceUpdateOne) check() error {
	if _u.mutation.StoreCleared() && len(_u.mutation.StoreIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "StoreFruitPrice.store"`)
	}
	return nil
}

func (_u *StoreFruitPriceUpdateOne) sqlSave(ctx context.Context) (_node *StoreFruitPrice, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(storefruitprice.Table, storefruitprice.Columns, sqlgraph.NewFieldSpec(storefruitprice.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StoreFruitPrice.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, storefruitprice.FieldID)
		for _, f := range fields {
			if !storefruitprice.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != storefruitprice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(storefruitprice.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(storefruitprice.FieldPrice, field.TypeFloat64, value)
	}
	if _u.mutation.StoreCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   storefruitprice.StoreTable,
			Columns: []string{storefruitprice.StoreColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(store.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StoreIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   storefruitprice.StoreTable,
			Columns: []string{storefruitprice.StoreColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(store.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &StoreFruitPrice{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{storefruitprice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
