server.port=8080
server.host=0.0.0.0
javax.sql.DataSource.fruits.dataSource.url=jdbc:postgresql://localhost:5432/fruits
javax.sql.DataSource.fruits.dataSource.user=fruits
javax.sql.DataSource.fruits.dataSource.password=fruits
javax.sql.DataSource.fruits.dataSourceClassName=org.postgresql.ds.PGSimpleDataSource
javax.sql.DataSource.fruits.poolName=helidon4-mp-jooq
javax.sql.DataSource.fruits.maximumPoolSize=50
javax.sql.DataSource.fruits.initializationFailTimeout=-1
javax.sql.DataSource.fruits.connectionTimeout=2000
metrics.rest-request.enabled=true
otel.sdk.disabled=false
otel.service.name=helidon4-mp-jooq
otel.traces.sampler=traceidratio
otel.traces.sampler.arg=0.1
otel.traces.exporter=otlp
otel.metrics.exporter=otlp
otel.exporter.otlp.endpoint=http://localhost:4317
